/**
 * VoteChain — Decentralized Voting DApp
 * ethers.js v6 + MetaMask integration
 */

// ─── Globals ────────────────────────────────────────────────────────────────

let provider = null;
let signer   = null;
let contract = null;
let userAddr = null;

// Loaded from contract.json (generated by deploy script)
let CONTRACT_ADDRESS = "";
let CONTRACT_ABI     = [];

// ─── DOM helpers ────────────────────────────────────────────────────────────

const $ = (id) => document.getElementById(id);
const el = (tag, cls, html) => {
  const e = document.createElement(tag);
  if (cls)  e.className   = cls;
  if (html) e.innerHTML   = html;
  return e;
};

function showToast(msg, type = "") {
  const t = $("toast");
  t.textContent = msg;
  t.className   = `toast ${type} show`;
  clearTimeout(t._timer);
  t._timer = setTimeout(() => { t.className = "toast"; }, 3500);
}

// ─── Load contract config ────────────────────────────────────────────────────

async function loadContractConfig() {
  try {
    const res  = await fetch("./contract.json");
    const data = await res.json();
    CONTRACT_ADDRESS = data.address;
    CONTRACT_ABI     = data.abi;
    return true;
  } catch {
    // contract.json not found — show helpful error
    showWalletAlert(
      "⚠️ contract.json not found. " +
      "Run <code>npx hardhat node</code> then <code>npx hardhat run scripts/deploy.js --network localhost</code> first."
    );
    return false;
  }
}

function showWalletAlert(msg) {
  const a = $("wallet-alert");
  a.innerHTML = `<span class="alert-icon">⚠️</span><div><strong>Setup Required</strong><p>${msg}</p></div>`;
  a.style.display = "flex";
}

// ─── Wallet connection ───────────────────────────────────────────────────────

async function connectWallet() {
  if (!window.ethereum) {
    showToast("MetaMask not detected! Please install it.", "error");
    return;
  }

  try {
    $("connect-btn").disabled = true;
    $("connect-label").textContent = "Connecting…";

    provider = new ethers.BrowserProvider(window.ethereum);
    await provider.send("eth_requestAccounts", []);
    signer   = await provider.getSigner();
    userAddr = await signer.getAddress();

    const network = await provider.getNetwork();
    updateHeaderConnected(network);

    // Build contract instance
    if (CONTRACT_ADDRESS && CONTRACT_ABI.length) {
      contract = new ethers.Contract(CONTRACT_ADDRESS, CONTRACT_ABI, signer);
    }

    updateHeroStats();
    showTabs();
    loadAllPolls();
    showToast("✅ Wallet connected!", "success");

    // Listen for account/chain changes
    window.ethereum.on("accountsChanged", handleAccountsChanged);
    window.ethereum.on("chainChanged",    () => location.reload());

  } catch (err) {
    console.error(err);
    showToast("Connection rejected.", "error");
    $("connect-btn").disabled = false;
    $("connect-label").textContent = "Connect Wallet";
  }
}

function handleAccountsChanged(accounts) {
  if (accounts.length === 0) {
    location.reload();
  } else {
    location.reload();
  }
}

function updateHeaderConnected(network) {
  const dot  = document.querySelector(".net-dot");
  const name = $("network-name");
  dot.classList.add("connected");
  name.textContent = network.name === "unknown"
    ? `Chain ${network.chainId}`
    : network.name.charAt(0).toUpperCase() + network.name.slice(1);

  $("connect-label").textContent =
    userAddr.slice(0, 6) + "…" + userAddr.slice(-4);
  $("connect-btn").disabled = false;

  $("wallet-alert").style.display = "none";
}

async function updateHeroStats() {
  if (!contract) return;
  try {
    const total = await contract.getTotalPolls();
    $("stat-polls").textContent = total.toString();
  } catch { /* ignore */ }

  $("stat-wallet").textContent = userAddr
    ? userAddr.slice(0, 6) + "…" + userAddr.slice(-4)
    : "Not connected";
}

function showTabs() {
  $("tabs").style.display = "flex";
}

// ─── Tab navigation ──────────────────────────────────────────────────────────

document.querySelectorAll(".tab").forEach(tab => {
  tab.addEventListener("click", () => {
    document.querySelectorAll(".tab").forEach(t => t.classList.remove("active"));
    document.querySelectorAll(".tab-section").forEach(s => s.classList.add("hidden"));

    tab.classList.add("active");
    const target = tab.getAttribute("data-target");
    $(target).classList.remove("hidden");

    if (target === "section-polls") loadAllPolls();
  });
});

$("refresh-btn").addEventListener("click", loadAllPolls);

// ─── Load all polls ──────────────────────────────────────────────────────────

async function loadAllPolls() {
  if (!contract) return;

  const grid    = $("polls-grid");
  const loading = $("polls-loading");
  const empty   = $("polls-empty");
  grid.innerHTML = "";
  loading.style.display = "flex";
  empty.style.display   = "none";

  try {
    const total = Number(await contract.getTotalPolls());
    await updateHeroStats();

    if (total === 0) {
      loading.style.display = "none";
      empty.style.display   = "flex";
      return;
    }

    // Load all polls in parallel
    const polls = await Promise.all(
      Array.from({ length: total }, (_, i) => contract.getPoll(i))
    );

    loading.style.display = "none";

    polls.forEach((p, i) => {
      grid.appendChild(buildPollCard(i, p));
    });

  } catch (err) {
    loading.style.display = "none";
    console.error("loadAllPolls error:", err);
    showToast("Failed to load polls.", "error");
  }
}

// ─── Build poll card ─────────────────────────────────────────────────────────

function buildPollCard(pollId, poll) {
  // poll = [id, creator, question, options[], votes[], deadline, active]
  const [, creator, question, options, votes, deadline, active] = poll;

  const totalVotes = votes.reduce((a, v) => a + Number(v), 0);
  const maxVotes   = Math.max(...votes.map(Number), 1);

  const card = el("div", "poll-card glass-card");
  card.setAttribute("id", `poll-card-${pollId}`);

  // Header
  const header = el("div", "poll-card-header");
  const q      = el("div", "poll-question", escHtml(question));
  const badge  = el("span",
    `poll-status ${active ? "status-active" : "status-ended"}`,
    active ? "ACTIVE" : "ENDED"
  );
  header.appendChild(q);
  header.appendChild(badge);
  card.appendChild(header);

  // Meta
  const meta = el("div", "poll-meta");
  const deadline_date = new Date(Number(deadline) * 1000);
  meta.innerHTML = `
    <span>🗳️ ${totalVotes} vote${totalVotes !== 1 ? "s" : ""}</span>
    <span>📋 ${options.length} options</span>
    <span>⏰ ${active ? "Ends" : "Ended"} ${formatDate(deadline_date)}</span>
  `;
  card.appendChild(meta);

  // Bar preview (top 3 options)
  const bars = el("div", "poll-bars");
  const top  = Math.min(3, options.length);
  for (let i = 0; i < top; i++) {
    const pct = totalVotes > 0 ? Math.round((Number(votes[i]) / totalVotes) * 100) : 0;
    const isWinner = Number(votes[i]) === maxVotes && totalVotes > 0;
    bars.innerHTML += `
      <div class="bar-row">
        <div class="bar-label-row">
          <span>${escHtml(options[i])}</span>
          <span>${pct}%</span>
        </div>
        <div class="bar-track">
          <div class="bar-fill ${isWinner ? "winner" : ""}" style="width:${pct}%"></div>
        </div>
      </div>
    `;
  }
  if (options.length > 3) {
    bars.innerHTML += `<p style="font-size:0.75rem;color:var(--text-dim);margin-top:4px">+${options.length - 3} more…</p>`;
  }
  card.appendChild(bars);

  // Footer
  const footer = el("div", "poll-card-footer");
  footer.innerHTML = `
    <span>Poll #${pollId}</span>
    <span class="view-link">View &amp; Vote →</span>
  `;
  card.appendChild(footer);

  card.addEventListener("click", () => openPollModal(pollId));
  return card;
}

// ─── Poll Detail Modal ────────────────────────────────────────────────────────

let selectedOption = null;

async function openPollModal(pollId) {
  selectedOption = null;
  $("modal-content").innerHTML = `<div class="loading-state"><div class="spinner"></div><p>Loading…</p></div>`;
  $("modal-overlay").style.display = "flex";

  try {
    const [, , question, options, votes, deadline, active] = await contract.getPoll(pollId);
    const alreadyVoted = await contract.didIVote(pollId);

    const totalVotes = votes.reduce((a, v) => a + Number(v), 0);
    const maxVotes   = Math.max(...votes.map(Number), 1);
    const deadline_date = new Date(Number(deadline) * 1000);

    let html = `
      <h2 class="modal-title" id="modal-title">${escHtml(question)}</h2>
      <div class="modal-sub">
        <span>${active ? "🟢 Active" : "🔴 Ended"}</span>
        <span>⏰ ${active ? "Ends" : "Ended"} ${formatDate(deadline_date)}</span>
        <span>🗳️ ${totalVotes} total vote${totalVotes !== 1 ? "s" : ""}</span>
      </div>
    `;

    if (alreadyVoted) {
      html += `<div class="voted-notice">✅ You have already voted on this poll</div>`;
      // Show results
      html += `<div class="result-bars">`;
      let userVotedIdx = -1;
      // Try to detect which option was voted — we can only know via events (simplified: just show all)
      for (let i = 0; i < options.length; i++) {
        const v   = Number(votes[i]);
        const pct = totalVotes > 0 ? Math.round((v / totalVotes) * 100) : 0;
        const isLeader = v === maxVotes && totalVotes > 0;
        html += `
          <div class="result-row">
            <div class="result-label-row">
              <span class="result-label">${escHtml(options[i])}</span>
              <span class="result-pct">${v} vote${v !== 1 ? "s" : ""} · ${pct}%</span>
            </div>
            <div class="result-track">
              <div class="result-fill ${isLeader ? "leader" : ""}" style="width:${pct}%"></div>
            </div>
          </div>
        `;
      }
      html += `</div>`;
      html += `<div class="modal-actions"><button class="btn btn-secondary" id="modal-close-btn">Close</button></div>`;

    } else if (!active) {
      // Poll ended, show results only
      html += `<div class="result-bars">`;
      for (let i = 0; i < options.length; i++) {
        const v   = Number(votes[i]);
        const pct = totalVotes > 0 ? Math.round((v / totalVotes) * 100) : 0;
        const isLeader = v === maxVotes && totalVotes > 0;
        html += `
          <div class="result-row">
            <div class="result-label-row">
              <span class="result-label">${escHtml(options[i])}</span>
              <span class="result-pct">${v} vote${v !== 1 ? "s" : ""} · ${pct}%</span>
            </div>
            <div class="result-track">
              <div class="result-fill ${isLeader ? "leader" : ""}" style="width:${pct}%"></div>
            </div>
          </div>
        `;
      }
      html += `</div>`;
      html += `<div class="modal-actions"><button class="btn btn-secondary" id="modal-close-btn">Close</button></div>`;

    } else {
      // Can vote
      html += `<div class="vote-options" id="vote-options-list">`;
      for (let i = 0; i < options.length; i++) {
        const v = Number(votes[i]);
        html += `
          <button class="vote-option" id="vote-opt-${i}" data-index="${i}" aria-label="Vote for ${escHtml(options[i])}">
            <div class="opt-radio"></div>
            <div class="opt-info">
              <div class="opt-label">${escHtml(options[i])}</div>
              <div class="opt-votes">${v} vote${v !== 1 ? "s" : ""} so far</div>
            </div>
          </button>
        `;
      }
      html += `</div>`;
      html += `
        <div id="vote-error" class="form-error" style="display:none"></div>
        <div class="modal-actions">
          <button class="btn btn-primary" id="cast-vote-btn">🗳️ Cast Vote</button>
          <button class="btn btn-secondary" id="modal-close-btn">Cancel</button>
        </div>
      `;
    }

    $("modal-content").innerHTML = html;

    // Bind option buttons
    document.querySelectorAll(".vote-option").forEach(btn => {
      btn.addEventListener("click", () => {
        document.querySelectorAll(".vote-option").forEach(b => b.classList.remove("selected"));
        btn.classList.add("selected");
        selectedOption = parseInt(btn.getAttribute("data-index"));
      });
    });

    // Cast vote
    const castBtn = $("cast-vote-btn");
    if (castBtn) {
      castBtn.addEventListener("click", () => castVote(pollId, castBtn));
    }

    // Close
    const closeBtn = $("modal-close-btn");
    if (closeBtn) closeBtn.addEventListener("click", closeModal);

  } catch (err) {
    console.error(err);
    $("modal-content").innerHTML = `<p style="color:var(--text-muted)">Failed to load poll details.</p>`;
  }
}

async function castVote(pollId, castBtn) {
  if (selectedOption === null) {
    const errEl = $("vote-error");
    if (errEl) { errEl.textContent = "Please select an option first."; errEl.style.display = "block"; }
    return;
  }

  castBtn.disabled = true;
  castBtn.innerHTML = `<div class="btn-spinner"></div> Confirming…`;

  try {
    showToast("Waiting for transaction…");
    const tx = await contract.vote(pollId, selectedOption);
    showToast("⏳ Transaction sent! Waiting for confirmation…");
    await tx.wait();
    showToast("✅ Vote cast successfully!", "success");
    closeModal();
    loadAllPolls();
  } catch (err) {
    console.error(err);
    const msg = err?.reason || err?.message || "Transaction failed.";
    const errEl = $("vote-error");
    if (errEl) { errEl.textContent = msg; errEl.style.display = "block"; }
    showToast("❌ Vote failed.", "error");
    castBtn.disabled = false;
    castBtn.innerHTML = `🗳️ Cast Vote`;
  }
}

function closeModal() {
  $("modal-overlay").style.display = "none";
}

$("modal-close").addEventListener("click", closeModal);
$("modal-overlay").addEventListener("click", (e) => {
  if (e.target === $("modal-overlay")) closeModal();
});

// ─── Create Poll form ────────────────────────────────────────────────────────

// Add option row
$("add-option-btn").addEventListener("click", () => {
  const container = $("options-container");
  const count = container.querySelectorAll(".option-input").length;
  if (count >= 10) { showToast("Maximum 10 options allowed.", "error"); return; }

  const row = el("div", "option-row");
  const letters = "ABCDEFGHIJ";
  row.innerHTML = `
    <input type="text" class="option-input" placeholder="Option ${letters[count]}" />
    <button type="button" class="remove-option" title="Remove">✕</button>
  `;
  row.querySelector(".remove-option").addEventListener("click", () => removeOption(row));
  container.appendChild(row);
  row.querySelector("input").focus();
});

// Remove option
function removeOption(row) {
  const container = $("options-container");
  if (container.querySelectorAll(".option-row").length <= 2) {
    showToast("Minimum 2 options required.", "error");
    return;
  }
  row.style.opacity = "0";
  row.style.transform = "translateX(-10px)";
  row.style.transition = "all 0.2s";
  setTimeout(() => row.remove(), 200);
}

// Wire up existing remove buttons
document.querySelectorAll(".remove-option").forEach(btn => {
  btn.addEventListener("click", () => removeOption(btn.closest(".option-row")));
});

// Submit create form
$("create-form").addEventListener("submit", async (e) => {
  e.preventDefault();

  if (!contract || !signer) {
    showToast("Connect your wallet first!", "error");
    return;
  }

  const question = $("poll-question").value.trim();
  const duration = parseInt($("poll-duration").value);
  const optInputs = document.querySelectorAll(".option-input");
  const options   = Array.from(optInputs).map(i => i.value.trim()).filter(Boolean);

  const errEl = $("create-error");
  errEl.style.display = "none";

  if (!question) {
    errEl.textContent = "Please enter a question."; errEl.style.display = "block"; return;
  }
  if (options.length < 2) {
    errEl.textContent = "Please enter at least 2 options."; errEl.style.display = "block"; return;
  }
  if (!duration || duration < 1) {
    errEl.textContent = "Duration must be at least 1 minute."; errEl.style.display = "block"; return;
  }

  const btn     = $("create-btn");
  const label   = $("create-btn-label");
  const spinner = $("create-spinner");

  btn.disabled       = true;
  label.style.display  = "none";
  spinner.style.display = "block";

  try {
    showToast("Waiting for MetaMask…");
    const tx = await contract.createPoll(question, options, duration);
    showToast("⏳ Transaction sent! Waiting…");
    await tx.wait();
    showToast("🎉 Poll created!", "success");

    // Reset form
    $("poll-question").value = "";
    $("poll-duration").value = "60";
    const container = $("options-container");
    container.innerHTML = `
      <div class="option-row">
        <input type="text" class="option-input" placeholder="Option A" />
        <button type="button" class="remove-option" title="Remove">✕</button>
      </div>
      <div class="option-row">
        <input type="text" class="option-input" placeholder="Option B" />
        <button type="button" class="remove-option" title="Remove">✕</button>
      </div>
    `;
    container.querySelectorAll(".remove-option").forEach(b => {
      b.addEventListener("click", () => removeOption(b.closest(".option-row")));
    });

    // Switch to polls tab
    $("tab-polls").click();

  } catch (err) {
    console.error(err);
    errEl.textContent = err?.reason || err?.message || "Transaction failed.";
    errEl.style.display = "block";
    showToast("❌ Failed to create poll.", "error");
  } finally {
    btn.disabled         = false;
    label.style.display  = "inline";
    spinner.style.display = "none";
  }
});

// ─── Connect button ──────────────────────────────────────────────────────────

$("connect-btn").addEventListener("click", connectWallet);

// ─── Helpers ─────────────────────────────────────────────────────────────────

function escHtml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatDate(date) {
  const now = new Date();
  const diff = Math.abs(date - now) / 1000;
  if (diff < 3600) return `${Math.ceil(diff / 60)}m`;
  if (diff < 86400) return `${Math.round(diff / 3600)}h`;
  return date.toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

// ─── Init ─────────────────────────────────────────────────────────────────────

async function init() {
  const ok = await loadContractConfig();
  if (!ok) return;

  // Auto-connect if already authorised
  if (window.ethereum) {
    const accounts = await window.ethereum.request({ method: "eth_accounts" });
    if (accounts.length > 0) {
      connectWallet();
    }
  } else {
    $("wallet-alert").style.display = "flex";
  }
}

init();

// TODO: live countdown timer for poll deadline

// Toast auto-dismisses after 3500ms
